import type { UserRole } from '../../types';

export type ExaminationPage = 'overview' | 'competitions' | 'sessions' | 'candidates' | 'registration-forms' | 'unmatched-transfers' | 'invigilation' | 'classes' | 'teachers' | 'partners' | 'import' | 'papers' | 'paper-create' | 'paper-detail' | 'blueprints' | 'blueprint-detail' | 'ai-config' | 'competition-detail' | 'session-detail' | 'candidate-detail' | 'class-detail' | 'teacher-detail';
export type DraftDate = { day: string; month: string; year: string; planned: boolean; unknown: boolean };
export type SessionRoundSlot = { id: string; label?: string; date?: string; time?: string; mode?: string; link?: string; location?: string; note?: string };
export type SessionRound = { id: string; name: string; label: string; date?: string; slots?: SessionRoundSlot[] };
export type ExaminationSession = { id: string; competitionId?: string; competitionName?: string; code: string; name: string; parent: string; organizer: string; time: string; candidates: number; national: string; nationalDate?: string; international: string; internationalDate?: string; phase: string; note: string; registrationSheetUrl?: string; registrationSheetTab?: string; academicYear?: string; outputSheetUrl?: string; outputSheetTab?: string; rounds?: SessionRound[]; updatedAt?: string; createdAt?: string };
export type CandidateExamHistory = { id?: string; sessionId?: string; sessionCode?: string; roundId?: string; occurrenceId?: string; round: string; eligibility?: string; sbd?: string; roomId?: string; roomName?: string; date?: string; time?: string; mode?: string; location?: string; link?: string; account?: string; password?: string; attendance?: string; score?: string; scoreRate?: string; rank?: string; result?: string; note?: string };
export type CandidateParticipation = { sessionId: string; sessionCode: string; sessionName: string; sessionTime: string; registration: { subject?: string; category?: string; registrationMethod?: string; registrationUnit?: string; teamName?: string; examLanguage?: string; generalNote?: string; certificateLink?: string; customAnswers?: { key: string; label: string; value: string }[] }; rounds: CandidateExamHistory[] };
export type Candidate = { code: string; name: string; school: string; className: string; city: string; ward?: string; nationality?: string; grade?: string; contests: string; subject?: string; category?: string; registrationMethod?: string; registrationUnit?: string; teamName?: string; examLanguage?: string; generalNote?: string; certificateLink?: string; achievement: string; highestRound?: string; updated: string; email: string; parent: string; phone: string; identity: string; address: string; birthDate: string; sessionIds?: string[]; participations?: CandidateParticipation[]; examHistory?: CandidateExamHistory[] };
export type Competition = { id: string; code: string; name: string; organizer: string; parent: string; updatedAt?: string; createdAt?: string };
export type TrainingClass = { id: string; sessionId: string; name: string; teacher: string; subject: string; startDate: string; endDate: string; schedule: { day: string; start: string; end: string }[]; candidateCodes: string[]; attendance: Record<string, 'Có mặt' | 'Vắng có phép' | 'Vắng'>; note: string };
export interface ExaminationModuleProps { onBackToWorkspace: () => void; onAccountClick: () => void; onLogout: () => void; userName?: string | null; userEmail?: string | null; photoURL?: string | null; idToken?: string | null; googleAccessToken?: string | null; userRole: UserRole; isGuest: boolean; }
export type CreateStep = 'choice' | 'competition' | 'ask' | 'session';
