import { ChevronDown, Search, X } from 'lucide-react';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { matchesSearch } from '../lib/searchText';

type Option = { value: string; label: string };
type Shared = { options: Option[]; placeholder?: string; searchPlaceholder?: string; className?: string };
type Props = Shared & ({ value: string; onChange: (value: string) => void; multiple?: false } | { value: string[]; onChange: (value: string[]) => void; multiple: true });

export default function SearchableSelect({ value, onChange, options, placeholder = 'Chọn mục', searchPlaceholder = 'Tìm kiếm trong bộ lọc...', className = '', multiple = false }: Props) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const root = useRef<HTMLDivElement>(null);
  const values = multiple ? value as string[] : [value as string]; const selected = options.filter(option => values.includes(option.value));
  const matches = useMemo(() => options.filter(option => matchesSearch(option.label, query)), [options, query]);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, []);
  const choose = (next: string) => { if (!multiple) { (onChange as (value: string) => void)(next); setOpen(false); return; } const current = value as string[]; (onChange as (value: string[]) => void)(next === '' ? [] : current.includes(next) ? current.filter(item => item !== next) : [...current, next]); };
  const label = multiple ? selected.length ? selected.map(item => item.label).join(', ') : placeholder : selected[0]?.label || placeholder;
  return <div ref={root} className={`relative min-w-0 ${className}`}><button type="button" onClick={() => { setOpen(item => !item); setQuery(''); }} className="flex w-full min-w-0 items-center justify-between gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-left text-sm text-slate-700"><span className="min-w-0 truncate">{label}</span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${open ? 'rotate-180' : ''}`}/></button>{open && <div className="absolute z-30 mt-1 w-full min-w-[240px] overflow-hidden rounded-lg border border-slate-300 bg-white shadow-xl"><div className="border-b p-2"><label className="flex items-center gap-2 rounded-md border border-slate-200 px-2 py-1.5"><Search className="h-4 w-4 text-slate-400"/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder={searchPlaceholder} className="min-w-0 flex-1 text-sm outline-none"/>{query && <button type="button" onClick={() => setQuery('')}><X className="h-3.5 w-3.5 text-slate-400"/></button>}</label></div><div className="max-h-52 overflow-y-auto py-1">{matches.map(option => { const active = values.includes(option.value); return <button type="button" key={option.value} onClick={() => choose(option.value)} className={`flex w-full items-center gap-2 px-3 py-2 text-left text-sm hover:bg-blue-50 ${active ? 'bg-blue-50 font-semibold text-blue-800' : 'text-slate-700'}`}>{multiple && <span className={`grid h-4 w-4 place-items-center rounded border ${active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-300'}`}>{active && '✓'}</span>}<span className="min-w-0 break-words">{option.label}</span></button>; })}{!matches.length && <p className="px-3 py-3 text-sm text-slate-500">Không có kết quả phù hợp.</p>}</div>{multiple && <div className="flex justify-between border-t bg-slate-50 px-3 py-2 text-xs"><button type="button" onClick={() => (onChange as (value: string[]) => void)([])} className="font-semibold text-slate-600">Xóa chọn</button><button type="button" onClick={() => setOpen(false)} className="font-bold text-blue-700">Xong</button></div>}</div>}</div>;
}
