# Generated by Codex for the weekly report workspace feature.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_key", models.CharField(max_length=180, unique=True)),
                ("employee_email", models.EmailField(blank=True, db_index=True, default="", max_length=254)),
                ("employee_name", models.CharField(max_length=255)),
                ("completed_week", models.PositiveSmallIntegerField(db_index=True)),
                ("planned_week", models.PositiveSmallIntegerField(db_index=True)),
                ("completed_items", models.JSONField(blank=True, default=list)),
                ("difficulties", models.JSONField(blank=True, default=list)),
                ("planned_items", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("snapshot", "Đã lấy từ lịch công tác"), ("published", "Đã cập nhật từ báo cáo AI")], default="snapshot", max_length=20)),
                ("google_document_id", models.CharField(blank=True, default="", max_length=180)),
                ("google_tab_id", models.CharField(blank=True, default="", max_length=180)),
                ("source_revision", models.CharField(blank=True, default="", max_length=500)),
                ("document_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-completed_week", "employee_name"]},
        ),
        migrations.AddIndex(
            model_name="weeklyreport",
            index=models.Index(fields=["completed_week", "planned_week", "employee_email"], name="weekly_report_period_email"),
        ),
    ]
