from django.urls import path

from . import assessment_views, views

urlpatterns = [
    path("digital-training/sessions", views.training_sessions, name="training_sessions"),
    path("digital-training/sessions/<int:pk>", views.training_session_detail, name="training_session_detail"),
    path("digital-training/customer-meetings", views.training_customer_meetings, name="training_customer_meetings"),
    path("digital-training/customer-meetings/<int:pk>", views.training_customer_meeting_detail, name="training_customer_meeting_detail"),
    path("digital-training/leads", views.training_leads, name="training_leads"),
    path("digital-training/leads/<int:pk>", views.training_lead_detail, name="training_lead_detail"),
    path("digital-training/leads/<int:pk>/convert", views.training_lead_convert, name="training_lead_convert"),
    path("digital-training/partners", views.training_partners, name="training_partners"),
    path("digital-training/partners/<int:pk>", views.training_partner_detail, name="training_partner_detail"),
    path("digital-training/classes", views.training_classes, name="training_classes"),
    path("digital-training/classes/<int:pk>", views.training_class_detail, name="training_class_detail"),
    path("digital-training/products", views.training_products, name="training_products"),
    path("digital-training/products/<int:pk>", views.training_product_detail, name="training_product_detail"),
    path("digital-training/product-subscriptions", views.training_product_subscriptions, name="training_product_subscriptions"),
    path("digital-training/finance-entries", views.training_finance_entries, name="training_finance_entries"),
    path("digital-training/finance-entries/<int:pk>", views.training_finance_entry_detail, name="training_finance_entry_detail"),
    path("digital-training/finance-partners", views.finance_partners, name="finance_partners"),
    path("digital-training/product-subscriptions/<int:pk>", views.training_product_subscription_detail, name="training_product_subscription_detail"),
    path("digital-training/product-opportunities", views.training_product_opportunities, name="training_product_opportunities"),
    path("digital-training/product-opportunities/<int:pk>", views.training_product_opportunity_detail, name="training_product_opportunity_detail"),
    path("digital-training/materials", views.training_materials, name="training_materials"),
    path("digital-training/materials/<int:pk>", views.training_material_detail, name="training_material_detail"),
    path("digital-training/surveys", views.training_surveys, name="training_surveys"),
    path("digital-training/surveys/<int:pk>", views.training_survey_detail, name="training_survey_detail"),
    path("digital-training/assessments", assessment_views.assessments, name="training_assessments"),
    path("digital-training/question-bank-settings", assessment_views.question_bank_settings, name="training_question_bank_settings"),
    path("digital-training/question-bank-snapshot", assessment_views.question_bank_snapshot, name="training_question_bank_snapshot"),
    path("digital-training/assessments/import-preview", assessment_views.assessment_import_preview, name="training_assessment_import_preview"),
    path("digital-training/assessments/<int:pk>", assessment_views.assessment_detail, name="training_assessment_detail"),
    path("digital-training/assessments/<int:pk>/variants", assessment_views.assessment_add_variants, name="training_assessment_add_variants"),
    path("digital-training/assessments/<int:pk>/results", assessment_views.assessment_results, name="training_assessment_results"),
    path("digital-training/assessment-previews/<slug:slug>", assessment_views.assessment_preview, name="training_assessment_preview"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>", assessment_views.assessment_result_grade, name="training_assessment_result_grade"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>/answers", assessment_views.assessment_result_answers, name="training_assessment_result_answers"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>/uploads/<int:upload_pk>/content", assessment_views.assessment_result_upload_content, name="training_assessment_result_upload_content"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>/kick", assessment_views.assessment_result_kick, name="training_assessment_result_kick"),
    path("digital-training/assessments/<int:pk>/prepare-output", assessment_views.assessment_prepare_output, name="training_assessment_prepare_output"),
    path("digital-training/assessments/<int:pk>/verify-backup", assessment_views.assessment_verify_backup, name="training_assessment_verify_backup"),
    path("digital-training/assessments-trash", assessment_views.assessment_trash, name="training_assessment_trash"),
    path("digital-training/assessments-trash/<int:pk>/restore", assessment_views.assessment_restore, name="training_assessment_restore"),
    path("digital-training/assessments/<int:pk>/import-sheet-grades", assessment_views.assessment_import_sheet_grades, name="training_assessment_import_sheet_grades"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>/storage", assessment_views.assessment_result_storage, name="training_assessment_result_storage"),
    path("digital-training/assessments/<int:pk>/results/<int:attempt_pk>/reopen", assessment_views.assessment_result_reopen, name="training_assessment_result_reopen"),
    path("digital-training/assessments/<int:pk>/results/sync-pending", assessment_views.assessment_sync_pending_results, name="training_assessment_sync_pending_results"),
    path("training-assessments/<slug:slug>", assessment_views.public_assessment, name="public_training_assessment"),
    path("training-assessments/<slug:slug>/start", assessment_views.public_assessment_start, name="public_training_assessment_start"),
    path("training-assessment-attempts/<uuid:token>", assessment_views.public_attempt, name="public_training_assessment_attempt"),
    path("training-assessment-attempts/<uuid:token>/upload", assessment_views.public_attempt_upload, name="public_training_assessment_upload"),
    path("training-assessment-attempts/<uuid:token>/uploads/<int:upload_pk>", assessment_views.public_attempt_upload_delete, name="public_training_assessment_upload_delete"),
]
