# Generated by Django 5.0.14 on 2026-09-17 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0033_backfill_sheet_room_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('hero_description', models.TextField(blank=True, default='')),
                ('hero_image_url', models.CharField(blank=True, default='', max_length=2000)),
                ('about_title', models.CharField(blank=True, default='', max_length=300)),
                ('about_body', models.TextField(blank=True, default='')),
                ('registration_url', models.CharField(blank=True, default='', max_length=2000)),
                ('registration_note', models.CharField(blank=True, default='', max_length=500)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=100)),
                ('contact_address', models.CharField(blank=True, default='', max_length=500)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('prizes', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('organizers', models.JSONField(blank=True, default=list)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='examination.competition')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
