# Generated by Django 5.0.14 on 2026-09-23 02:48

from django.db import migrations, models
from examination.landing_templates import olympiad_content


def seed_first_template(apps, schema_editor):
    LandingTemplate = apps.get_model('examination', 'LandingTemplate')
    LandingSite = apps.get_model('examination', 'LandingSite')
    LandingTemplate.objects.get_or_create(
        key='olympiad',
        defaults={
            'name': 'Mẫu 1 · Olympic học thuật',
            'description': 'Bố cục xanh dương cho trang FIMO, FIEO và các cuộc thi học thuật.',
            'layout': 'olympiad',
            'content': olympiad_content('FIMO'),
            'is_system': True,
        },
    )
    LandingSite.objects.filter(template='custom').update(template='olympiad')


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0035_landingsite_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('layout', models.CharField(default='olympiad', max_length=40)),
                ('content', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='landingsite',
            name='layout',
            field=models.CharField(default='olympiad', max_length=40),
        ),
        migrations.AlterField(
            model_name='landingsite',
            name='template',
            field=models.CharField(default='olympiad', max_length=40),
        ),
        migrations.RunPython(seed_first_template, migrations.RunPython.noop),
    ]
