# Generated by Django 5.0.14 on 2026-09-28 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_billing(apps, schema_editor):
    Participation = apps.get_model('examination', 'CandidateParticipation')
    Billing = apps.get_model('examination', 'ExaminationBillingRecord')
    Billing.objects.bulk_create(
        [Billing(participation_id=pk, seen_by_accountant=True)
         for pk in Participation.objects.values_list('pk', flat=True).iterator()],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0041_remove_landing_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('transfer_status', models.CharField(default='pending', max_length=20)),
                ('transfer_reference', models.CharField(blank=True, default='', max_length=255)),
                ('transfer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_confirmed_by', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_status', models.CharField(default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_checked_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_checked_by', models.CharField(blank=True, default='', max_length=255)),
                ('seen_by_accountant', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='examination.candidateparticipation')),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('image_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(max_length=255)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examination.candidateparticipation')),
            ],
        ),
        migrations.RunPython(backfill_billing, migrations.RunPython.noop),
    ]
