# Generated by Django 5.0.14 on 2026-09-28 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0042_examinationbillingrecord_unmatchedtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=100)),
                ('sheet_tab', models.CharField(max_length=255)),
                ('source_uid', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='formregistrationlink',
            constraint=models.UniqueConstraint(fields=('spreadsheet_id', 'sheet_tab', 'source_uid', 'session'), name='unique_form_registration_session'),
        ),
    ]
