# Generated by Django 5.0.14 on 2026-09-28 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0044_link_2026_2027_registration_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicExamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField(unique=True)),
                ('contest_codes', models.JSONField(default=list)),
                ('payment_declared', models.BooleanField(default=False)),
                ('proof', models.BinaryField(blank=True, null=True)),
                ('proof_type', models.CharField(blank=True, default='', max_length=50)),
                ('sheet_rows', models.JSONField(blank=True, default=dict)),
                ('sheet_status', models.CharField(default='pending', max_length=20)),
                ('sheet_error', models.TextField(blank=True, default='')),
                ('source_ip_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_registrations', to='examination.candidate')),
            ],
        ),
    ]
