# Generated by Django 5.0.14 on 2026-09-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0046_landing_reference_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistrationPage',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('draft_content', models.JSONField(blank=True, default=dict)),
                ('published_content', models.JSONField(blank=True, default=dict)),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
