# Generated by Django 5.0.14 on 2026-10-01 02:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0049_enable_registration_source_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSheetOutbox',
            fields=[
                ('candidate_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('revision', models.UUIDField(default=uuid.uuid4)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
