# Generated by Django 5.0.14 on 2026-10-01 02:50

import uuid
from django.db import migrations, models


def queue_existing_memberships(apps, schema_editor):
    Sheet = apps.get_model('examination', 'ExaminationSheet')
    Candidate = apps.get_model('examination', 'Candidate')
    Participation = apps.get_model('examination', 'CandidateParticipation')
    SessionQueue = apps.get_model('examination', 'SessionSheetOutbox')
    ContactQueue = apps.get_model('examination', 'CandidateSheetOutbox')
    session_ids = set(Sheet.objects.filter(stage__in=['session-output', 'registration-source']).exclude(
        url='').exclude(sheet_tab='').exclude(url__contains='1gqO1Tp4YSBp0UVBgXjJgvL8CuqftVKGNd74PPRX9i8E'
    ).values_list('session_id', flat=True))
    memberships = set(Participation.objects.filter(session_id__in=session_ids).values_list('candidate_id', 'session_id'))
    for candidate in Candidate.objects.all().only('id', 'session_ids'):
        memberships.update((candidate.pk, session_id) for session_id in (candidate.session_ids or []) if session_id in session_ids)
    SessionQueue.objects.bulk_create([SessionQueue(candidate_id=candidate_id, session_id=session_id)
        for candidate_id, session_id in memberships], ignore_conflicts=True)
    ContactQueue.objects.bulk_create([ContactQueue(candidate_id=candidate_id)
        for candidate_id in {candidate_id for candidate_id, _ in memberships}], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0050_candidate_sheet_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSheetOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('revision', models.UUIDField(default=uuid.uuid4)),
                ('enqueued_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sessionsheetoutbox',
            constraint=models.UniqueConstraint(fields=('candidate_id', 'session_id'), name='unique_session_sheet_outbox'),
        ),
        migrations.RunPython(queue_existing_memberships, migrations.RunPython.noop),
    ]
