# Generated by Django 5.0.14 on 2026-10-03 03:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0051_session_sheet_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
                ('image_type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_status', models.CharField(default='pending_configuration', max_length=30)),
                ('drive_error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='examinationbillingrecord',
            name='participation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='examination.candidateparticipation'),
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('contact', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examination.examsession')),
            ],
        ),
        migrations.AddField(
            model_name='candidateparticipation',
            name='school_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='examination.schoolregistration'),
        ),
        migrations.AddField(
            model_name='examinationbillingrecord',
            name='school_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='examination.schoolregistration'),
        ),
        migrations.AddConstraint(
            model_name='examinationbillingrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('participation__isnull', False), ('school_registration__isnull', True)), models.Q(('participation__isnull', True), ('school_registration__isnull', False)), _connector='OR'), name='billing_has_one_owner'),
        ),
        migrations.AddField(
            model_name='transferproof',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='examination.examinationbillingrecord'),
        ),
        migrations.AddField(
            model_name='transferproof',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='examination.examsession'),
        ),
        migrations.AddField(
            model_name='transferproof',
            name='unmatched',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='examination.unmatchedtransfer'),
        ),
        migrations.AddConstraint(
            model_name='schoolregistration',
            constraint=models.UniqueConstraint(fields=('partner_id', 'session'), name='unique_school_registration_session'),
        ),
        migrations.AddConstraint(
            model_name='transferproof',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('billing__isnull', False), ('unmatched__isnull', True)), models.Q(('billing__isnull', True), ('unmatched__isnull', False)), _connector='OR'), name='proof_has_one_owner'),
        ),
    ]
