# Generated by Django 5.0.14 on 2026-10-08 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_update_september_attendance_sheet_link'),
        ('examination', '0053_clear_sheet_manual_review_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInvigilationShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_id', models.CharField(max_length=255)),
                ('round_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=100)),
                ('room_link', models.CharField(blank=True, default='', max_length=2000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('invigilator_label', models.CharField(blank=True, default='', max_length=255)),
                ('sheet_url', models.CharField(blank=True, default='', max_length=2000)),
                ('sheet_tab', models.CharField(blank=True, default='', max_length=255)),
                ('roster', models.JSONField(blank=True, default=list)),
                ('pending_sheet_rows', models.JSONField(blank=True, default=dict)),
                ('sheet_error', models.TextField(blank=True, default='')),
                ('revision', models.UUIDField(default=uuid.uuid4)),
                ('demo', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invigilators', models.ManyToManyField(blank=True, related_name='exam_duties', to='authentication.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_shifts', to='examination.examsession')),
            ],
            options={
                'ordering': ['starts_at', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamInvigilationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_code', models.CharField(max_length=255)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='examination.examinvigilationshift')),
            ],
        ),
        migrations.AddConstraint(
            model_name='examinvigilationshift',
            constraint=models.UniqueConstraint(fields=('session', 'occurrence_id', 'room_number'), name='unique_invigilation_shift_room'),
        ),
        migrations.AddConstraint(
            model_name='examinvigilationshift',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='invigilation_ends_after_start'),
        ),
    ]
