# Generated by Django 5.0.14 on 2026-10-08 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0054_examinvigilationshift_examinvigilationaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinvigilationshift',
            name='exam_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilation_shifts', to='examination.examroom'),
        ),
    ]
