# Generated by Django 5.0.14 on 2026-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0055_invigilation_shift_exam_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundresult',
            name='eligibility',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
